version: "3.9"

services:
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: ${KAFKA_UI_CONTAINER_NAME:-kafka-ui-app}
    ports:
      - "8080:8080"
    environment:
      # The UI listens on SERVER_PORT (default 8080)
      - SERVER_PORT=8080
      # Minimal required cluster configuration (edit these or use an env file)
      - KAFKA_CLUSTERS_0_NAME=${KAFKA_CLUSTERS_0_NAME:-cluster-1}
      - KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS=${KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS:-localhost:9092}
      # Optional: Enable adding clusters dynamically via the UI
      - DYNAMIC_CONFIG_ENABLED=${DYNAMIC_CONFIG_ENABLED:-true}
    env_file:
      - .env

  producer:
    build: ./producer
    container_name: ${PRODUCER_CONTAINER_NAME:-kafka-producer-app}
    environment:
      - PORT=3000
      - KAFKA_CLIENT_ID=${PRODUCER_KAFKA_CLIENT_ID:-producer-app}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-localhost:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-demo-topic}
      - PRODUCER_INTERVAL_MS=${PRODUCER_INTERVAL_MS:-2000}
      - KAFKA_SECURITY_PROTOCOL=${KAFKA_SECURITY_PROTOCOL}
      - KAFKA_SASL_MECHANISM=${KAFKA_SASL_MECHANISM}
      - KAFKA_SASL_USERNAME=${KAFKA_SASL_USERNAME}
      - KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - KAFKA_SSL=${KAFKA_SSL}
    ports:
      - "3001:3000"
    env_file:
      - .env

  consumer:
    build: ./consumer
    container_name: ${CONSUMER_CONTAINER_NAME:-kafka-consumer-app}
    environment:
      - PORT=3000
      - KAFKA_CLIENT_ID=${CONSUMER_KAFKA_CLIENT_ID:-consumer-app}
      - KAFKA_GROUP_ID=${KAFKA_GROUP_ID:-demo-group}
      - KAFKA_BROKERS=${KAFKA_BROKERS:-localhost:9092}
      - KAFKA_TOPIC=${KAFKA_TOPIC:-demo-topic}
      - KAFKA_SECURITY_PROTOCOL=${KAFKA_SECURITY_PROTOCOL}
      - KAFKA_SASL_MECHANISM=${KAFKA_SASL_MECHANISM}
      - KAFKA_SASL_USERNAME=${KAFKA_SASL_USERNAME}
      - KAFKA_SASL_PASSWORD=${KAFKA_SASL_PASSWORD}
      - KAFKA_SSL=${KAFKA_SSL}
    ports:
      - "3002:3000"
    env_file:
      - .env
